import java.util.*;

public class Online {
	static Scanner s = new Scanner(System.in);

	private static void exam(String n){
			int c,marks = 0;
			
					System.out.println("Q.\nWho is known as father of Java Programming Language?\n"
							+ "1.James Gosling \n2.M. P Java\n3.Charel Babbage \n4.Blais Pascal");
					System.out.print("Enter answer:");
		            c=s.nextInt();   
		            if(c==1)
		            	marks+=10;
		
					System.out.println("Q.\nIn java control statements break, continue, return, try-catch-finally and assert belongs to?\n"
							+ "1.Selection statements \n2.Loop Statements\n3.Transfer statements \n4.Pause Statement");
					System.out.print("Enter answer:");
		            c=s.nextInt();   
		            if(c==3)
		            	marks+=10;

					System.out.println("Q.\n Which provides runtime environment for java byte code to be executed?\n"
							+ "1.JDK\n2.JVM"
							+ "\n3.JRE\n4.JAVAC");
					System.out.print("Enter answer:");
		            c=s.nextInt();   
		            if(c==2)
		            	marks+=10;

					System.out.println("Q.\nWhat is byte code in Java?\n"
							+ "1.Code generated by a Java compiler\n2.Code generated by a Java Virtual Machine"
							+ "\n3.Name of Java source code file\n4.Block of code written inside a class");
					System.out.print("Enter answer:");
		            c=s.nextInt();   
		            if(c==1)
		            	marks+=10;

					System.out.println("Q.\nWhich of the following are not Java keywords ?\n"
							+ "1.double\n2.switch"
							+ "\n3.then\n4.instanceof");
					System.out.print("Enter answer:");
		            c=s.nextInt();   
		            if(c==3)
		            	marks+=10;
				
			 System.out.println("Congrats !!\n  Your scored is "+marks+" marks"+" out of 50");			
		}

	public static void main(String[] args) {
		System.out.println("   Welcome to online V examination   ");
		System.out.print("Enter user name:");
		String n = s.next();
		System.out.print("Enter roll no:");
		int id = s.nextInt();
		exam(n);

	}

}
